In [11]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.1.0'

In [38]:
A = tf.constant(17.)
B = tf.constant([[1, 2, 3,],  [4, 5, 6, ]])
C = tf.constant([[11, 12, 13,],  [41, 51, 61 ]])
D = tf.constant([7.])
E = tf.constant([[11, 12],  [41, 51]])

In [26]:
print (A, B)

tf.Tensor(17.0, shape=(), dtype=float32) tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [27]:
np_one = np.ones((4, 5))
tf_one = tf.ones((4, 5))

In [28]:
tf_one.numpy() == np_one

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [40]:
print ('TFmatMul', tf.matmul(E, C))

TFmatMul tf.Tensor(
[[ 613  744  875]
 [2542 3093 3644]], shape=(2, 3), dtype=int32)


In [32]:
add = tf.add(B, C)
subtract = tf.subtract(B, C)
multiply = tf.multiply(B, C)
divide = tf.divide(B, C)

In [33]:
print (add, subtract, multiply, divide)

tf.Tensor(
[[12 14 16]
 [45 56 67]], shape=(2, 3), dtype=int32) tf.Tensor(
[[-10 -10 -10]
 [-37 -46 -55]], shape=(2, 3), dtype=int32) tf.Tensor(
[[ 11  24  39]
 [164 255 366]], shape=(2, 3), dtype=int32) tf.Tensor(
[[0.09090909 0.16666667 0.23076923]
 [0.09756098 0.09803922 0.09836066]], shape=(2, 3), dtype=float64)


In [36]:
y = tf.constant([1, 3, 5])
print ('mean', tf.reduce_mean(y))
print ('min', tf.reduce_min(y))
print ('max', tf.reduce_max(y))

mean tf.Tensor(3, shape=(), dtype=int32)
min tf.Tensor(1, shape=(), dtype=int32)
max tf.Tensor(5, shape=(), dtype=int32)


In [45]:
features = tf.random.uniform((3, 3), minval=0, maxval=10)
weights = tf.random.normal((3, 10))
bias = tf.random.normal((3, 1))
output = tf.add(tf.matmul(features, weights), bias)

In [46]:
print (features, weights, bias, output)

tf.Tensor(
[[7.398     6.3015785 8.845395 ]
 [1.9855487 2.3385918 7.9309487]
 [4.245023  6.3662186 4.868556 ]], shape=(3, 3), dtype=float32) tf.Tensor(
[[ 1.1126157  -0.3004477   0.70295906  0.7492183  -0.10945582  1.5267467
   0.03086453 -0.23403946 -1.0356838  -0.7542479 ]
 [ 1.5040975  -1.0239305  -0.66952103 -0.03673423 -0.7799987  -0.19792837
   0.2801368  -0.9983823  -0.5246867   1.3342627 ]
 [ 1.0265418  -0.38877496  0.9427757   0.42132005  0.19741133 -1.0311329
  -1.2954727   0.8051268   3.0421944  -0.68142426]], shape=(3, 10), dtype=float32) tf.Tensor(
[[ 0.13521542]
 [-0.33511066]
 [ 1.7952672 ]], shape=(3, 1), dtype=float32) tf.Tensor(
[[ 26.924704   -11.978744     9.455891     9.173191    -3.8435807
    1.0620484   -9.330112    -0.76592815  16.076284    -3.0642164 ]
 [ 13.532963    -6.409574     6.9720182    4.40806     -0.81088006
   -5.944417    -9.89303      3.2508035   20.50895     -4.1167517 ]
 [ 21.091536    -7.8914785    5.1069837    6.793078    -2.6739097
    1.9961

In [ ]:
# TODO: ganti nilai weight1, weight2, dan bias
weight1 = 1
weight2 = 1
bias = 0

# SCRIPT DIBAWAH HARAP JANGAN DIUBAH
# Input Output
test_inputs = [(1, 1), (0, 1), (1, 0), (0, 0)]
outputs = []

## AND
# targets = [True, False, False, False]

## OR
targets = [1, 1, 1, 0]

# Generate hasil
for inputs, target in zip(test_inputs, targets):
    linear_combination = weight1*inputs[0] + weight2*inputs[1] + bias
    output = int(linear_combination > 0)
    is_correct = 'Benar' if output == target else 'Salah'
    outputs.append(
        [inputs[0], inputs[1], linear_combination, output, is_correct]
    )

# Tampilkan hasil
num_wrong = len([output[4] for output in outputs if output[4] == "Salah"])
output_df = pd.DataFrame(
    outputs,
    columns=[
        'Input X1', 'Input X2', 'Linear Combination',
        'Activation Output', 'Is Correct'
    ]
)
if not num_wrong:
    print("Nice! Perceptron bekerja sesuai harapan.\n")
else:
    print(f"Ada {num_wrong} kesalahan. Terus mencoba.\n")
print(output_df.to_string(index=False))

In [53]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

def plot_points(X, y):
    admitted = X[np.argwhere(y==1)]
    rejected = X[np.argwhere(y==0)]
    plt.scatter(
        [s[0][0] for s in rejected],
        [s[0][1] for s in rejected], s = 25, color = 'blue', edgecolor = 'k'
    )
    plt.scatter(
        [s[0][0] for s in admitted],
        [s[0][1] for s in admitted], s = 25, color = 'red', edgecolor = 'k'
    )

def display(m, b, color='g--'):
    plt.xlim(-0.05,1.05)
    plt.ylim(-0.05,1.05)
    x = np.arange(-10, 10, 0.1)
    plt.plot(x, m*x+b, color)

In [91]:
data = pd.read_csv('data.csv', header=None)
X = np.array(data[[0,1]])
X = tf.convert_to_tensor(X)
y = tf.convert_to_tensor(data[2])
# plot_points(X,y)
# plt.show()

In [92]:
X

<tf.Tensor: shape=(100, 2), dtype=float64, numpy=
array([[ 0.78051  , -0.063669 ],
       [ 0.28774  ,  0.29139  ],
       [ 0.40714  ,  0.17878  ],
       [ 0.2923   ,  0.4217   ],
       [ 0.50922  ,  0.35256  ],
       [ 0.27785  ,  0.10802  ],
       [ 0.27527  ,  0.33223  ],
       [ 0.43999  ,  0.31245  ],
       [ 0.33557  ,  0.42984  ],
       [ 0.23448  ,  0.24986  ],
       [ 0.0084492,  0.13658  ],
       [ 0.12419  ,  0.33595  ],
       [ 0.25644  ,  0.42624  ],
       [ 0.4591   ,  0.40426  ],
       [ 0.44547  ,  0.45117  ],
       [ 0.42218  ,  0.20118  ],
       [ 0.49563  ,  0.21445  ],
       [ 0.30848  ,  0.24306  ],
       [ 0.39707  ,  0.44438  ],
       [ 0.32945  ,  0.39217  ],
       [ 0.40739  ,  0.40271  ],
       [ 0.3106   ,  0.50702  ],
       [ 0.49638  ,  0.45384  ],
       [ 0.10073  ,  0.32053  ],
       [ 0.69907  ,  0.37307  ],
       [ 0.29767  ,  0.69648  ],
       [ 0.15099  ,  0.57341  ],
       [ 0.16427  ,  0.27759  ],
       [ 0.33259  ,  0.055

In [93]:
# Activation (sigmoid) function
def sigmoid(x):
    return 1 / (1+ tf.math.exp(-x))

# Output (prediction) formula
def output_formula(features, weights, bias):
    y_pred = sigmoid(tf.matmul(features, weights) + bias)
    return y_pred

# # Activation softmax fx
# def softmax(x):
#     return np.exp(x)/np.sum(np.exp(x))
    
# # Output (prediction) formula
# def output_formula_softmax(features, weights, bias):
#     y_pred = softmax(np.matmul(features, weights) + bias)
#     return y_pred


# Error (log-loss) formula
def error_formula(y, output):
    error = -( y*tf.math.log1p(output) + tf.multiply((1-y), (tf.math.log10(1-output))) )
    return error    

# Gradient descent step
def update_weights(x, y, weights, bias, learnrate):
    output = output_formula_softmax(x, weights, bias)
#     output = output_formula_sigmoid(x, weights, bias)
    new_weights = weights + learnrate*(y-output)*x
    new_bias = bias + learnrate*(y-output)
    return new_weights, new_bias
    

In [94]:
np.random.seed(44)

epochs = 500
learnrate = 0.00001

def train(features, targets, epochs, learnrate, graph_lines=False):
    errors = []
    n_records, n_features = features.shape
    last_loss = None
#     weights = np.random.normal(scale=1 / n_features**.5, size=n_features)
    weights = tf.random.normal((n_records, n_features), stddev=1/(n_features**.5))
    print (features, weights)
    bias = 0
    for e in range(epochs):
        del_w = np.zeros(weights.shape)
        for x, y in zip(features, targets):
            output = output_formula(x, weights, bias)
            error = error_formula(y, output)
            weights, bias = update_weights(x, y, weights, bias, learnrate)
        
        # Printing out the log-loss error on the training set
        out = output_formula(features, weights, bias)
        loss = tf.math.mean(error_formula(targets, out))
        errors.append(loss)
        if e % (epochs / 10) == 0:
            print("\n========== Epoch", e,"==========")
            if last_loss and last_loss < loss:
                print("Train loss: ", loss, "  WARNING - Loss Increasing")
            else:
                print("Train loss: ", loss)
            last_loss = loss
            predictions = out > 0.5
            accuracy = np.mean(predictions == targets)
            print("Accuracy: ", accuracy)
        if graph_lines and e % (epochs / 100) == 0:
            display(-weights[0]/weights[1], -bias/weights[1])

    # Plotting the solution boundary
    plt.title("Solution boundary")
    display(-weights[0]/weights[1], -bias/weights[1], 'black')

    # Plotting the data
    plot_points(features, targets)
    plt.show()

    # Plotting the error
    plt.title("Error Plot")
    plt.xlabel('Number of epochs')
    plt.ylabel('Error')
    plt.plot(errors)
    plt.show()

In [95]:
train(X, y, epochs, learnrate, True)

tf.Tensor(
[[ 0.78051   -0.063669 ]
 [ 0.28774    0.29139  ]
 [ 0.40714    0.17878  ]
 [ 0.2923     0.4217   ]
 [ 0.50922    0.35256  ]
 [ 0.27785    0.10802  ]
 [ 0.27527    0.33223  ]
 [ 0.43999    0.31245  ]
 [ 0.33557    0.42984  ]
 [ 0.23448    0.24986  ]
 [ 0.0084492  0.13658  ]
 [ 0.12419    0.33595  ]
 [ 0.25644    0.42624  ]
 [ 0.4591     0.40426  ]
 [ 0.44547    0.45117  ]
 [ 0.42218    0.20118  ]
 [ 0.49563    0.21445  ]
 [ 0.30848    0.24306  ]
 [ 0.39707    0.44438  ]
 [ 0.32945    0.39217  ]
 [ 0.40739    0.40271  ]
 [ 0.3106     0.50702  ]
 [ 0.49638    0.45384  ]
 [ 0.10073    0.32053  ]
 [ 0.69907    0.37307  ]
 [ 0.29767    0.69648  ]
 [ 0.15099    0.57341  ]
 [ 0.16427    0.27759  ]
 [ 0.33259    0.055964 ]
 [ 0.53741    0.28637  ]
 [ 0.19503    0.36879  ]
 [ 0.40278    0.035148 ]
 [ 0.21296    0.55169  ]
 [ 0.48447    0.56991  ]
 [ 0.25476    0.34596  ]
 [ 0.21726    0.28641  ]
 [ 0.67078    0.46538  ]
 [ 0.3815     0.4622   ]
 [ 0.53838    0.32774  ]
 [ 0.4849     

InvalidArgumentError: cannot compute MatMul as input #1(zero-based) was expected to be a double tensor but is a float tensor [Op:MatMul] name: MatMul/